import fs from "fs";
import path from "path";
import pc from "picocolors";
import * as p from "@clack/prompts";
import { scanProject } from "../core/scanner.js";
import { loadConfig, findConfigFile, parseEnvContent } from "../../runtime/config.js";
import { promptVariableClassification } from "../ui/prompts.js";

export interface SyncCommandOptions {
  cwd?: string;
  config?: string;
  yes?: boolean;
  example?: boolean; // Generate/update .env.example
  prune?: boolean;   // Remove unused variables from contract
}

export async function runSync(options: SyncCommandOptions = {}): Promise<void> {
  const cwd = options.cwd || process.cwd();
  const isAutoYes = Boolean(options.yes);

  if (!isAutoYes) {
    p.intro(pc.bgCyan(pc.black(" EnvBoot Sync ")));
  }

  // 1. Scan codebase and env files
  const spinner = isAutoYes ? null : p.spinner();
  if (spinner) spinner.start("Scanning codebase for environment variables...");

  const scanResult = await scanProject(cwd);
  const configPath = findConfigFile(cwd, options.config) || path.join(cwd, ".envboot.json");
  const existingConfig = fs.existsSync(configPath) ? loadConfig(options.config, cwd) : { required: [], optional: [] };

  if (spinner) {
    spinner.stop(
      `Scanned ${scanResult.scannedFilesCount} files. Found ${scanResult.variables.size} unique variable(s).`
    );
  }

  const existingRequired = new Set(existingConfig?.required || []);
  const existingOptional = new Set(existingConfig?.optional || []);
  const existingAll = new Set([...existingRequired, ...existingOptional]);

  // Find newly added variables
  const allDiscoveredVars = Array.from(scanResult.variables.keys()).sort();
  const newlyAddedVars = allDiscoveredVars.filter((v) => !existingAll.has(v));

  // Find removed/dead variables
  const discoveredSet = new Set(allDiscoveredVars);
  const deadVars = Array.from(existingAll).filter((v) => !discoveredSet.has(v));

  if (newlyAddedVars.length === 0 && deadVars.length === 0) {
    if (!isAutoYes) {
      p.outro(pc.green("✔ Environment contract is already in sync with codebase!"));
    } else {
      console.log(pc.green("✔ Environment contract is already in sync with codebase!"));
    }
    syncEnvExample(cwd, allDiscoveredVars);
    return;
  }

  let finalRequired = new Set(existingRequired);
  let finalOptional = new Set(existingOptional);

  // Classify new variables
  if (newlyAddedVars.length > 0) {
    if (isAutoYes) {
      // In auto mode, new variables found in code default to required
      for (const v of newlyAddedVars) {
        finalRequired.add(v);
      }
    } else {
      p.log.info(`Found ${pc.bold(newlyAddedVars.length.toString())} new environment variable(s) in codebase.`);
      const classification = await promptVariableClassification(newlyAddedVars);
      for (const v of classification.required) finalRequired.add(v);
      for (const v of classification.optional) finalOptional.add(v);
    }
  }

  // Handle dead variables
  if (deadVars.length > 0 && options.prune) {
    for (const v of deadVars) {
      finalRequired.delete(v);
      finalOptional.delete(v);
    }
  }

  // Save updated config
  const newConfig = {
    required: Array.from(finalRequired).sort(),
    optional: Array.from(finalOptional).sort(),
    ignore: existingConfig?.ignore || ["NODE_ENV", "TZ"],
  };

  fs.writeFileSync(configPath, JSON.stringify(newConfig, null, 2) + "\n", "utf-8");

  // Sync .env.example
  syncEnvExample(cwd, Array.from(new Set([...finalRequired, ...finalOptional])).sort());

  // Report sync results
  if (!isAutoYes) {
    let summary = `${pc.green("✔")} Contract synced to ${pc.cyan(".envboot.json")}\n\n`;
    if (newlyAddedVars.length > 0) {
      summary += `  ${pc.bold("Added:")} ${pc.green(newlyAddedVars.join(", "))}\n`;
    }
    if (deadVars.length > 0) {
      if (options.prune) {
        summary += `  ${pc.bold("Pruned:")} ${pc.red(deadVars.join(", "))}\n`;
      } else {
        summary += `  ${pc.dim(`Unused (kept): ${deadVars.join(", ")} (run with --prune to remove)`)}\n`;
      }
    }
    summary += `  ${pc.bold("Updated:")} ${pc.cyan(".env.example")}\n`;
    p.outro(summary);
  } else {
    console.log(pc.green("✔ Environment contract synced successfully!"));
  }
}

function syncEnvExample(cwd: string, variables: string[]): void {
  const examplePath = path.join(cwd, ".env.example");
  let existingKeys = new Set<string>();

  if (fs.existsSync(examplePath)) {
    try {
      const content = fs.readFileSync(examplePath, "utf-8");
      const parsed = parseEnvContent(content);
      existingKeys = new Set(Object.keys(parsed));
    } catch {
      // ignore
    }
  }

  const lines: string[] = [];
  if (fs.existsSync(examplePath)) {
    const raw = fs.readFileSync(examplePath, "utf-8").trim();
    if (raw) lines.push(raw);
  } else {
    lines.push("# Environment Template generated by EnvBoot");
  }

  let addedCount = 0;
  for (const v of variables) {
    if (!existingKeys.has(v)) {
      lines.push(`${v}=`);
      addedCount++;
    }
  }

  if (addedCount > 0 || !fs.existsSync(examplePath)) {
    fs.writeFileSync(examplePath, lines.join("\n") + "\n", "utf-8");
  }
}
